// Generated by scripts/fetch-fixtures.mjs on 2026-09-25 from what Pyth's own contract
// on Arbitrum (0xff1a0f4744e8582DF1aE09D5611b887B6a12925C) trusts. Pinned in code: changing it means shipping a new contract version.
export const TRUST_ANCHOR = {
    // Signers of Pyth's Wormhole-compatible receiver 0x8d289cdd60e7f73f352f42c8524a06ef1ad746f8.
    // Quorum is 1/2 + 1, matching ReceiverImplementationHalf.sol in pyth-network/pyth-crosschain.
    guardianSets: {
        1: {
            quorum: 3,
            keys: [
                '41534bb176e461a3fb30479400f210549ecce638',
                '6502987b62f21cab7eb5ccd8f0173084b60d5b41',
                '44a3e8f6a382412cf6bb90a3f8106e68977476c9',
                '13edc776d3063549fdb0702af182edc905a539d4',
                '3af088854bb768065f4929e5bbdfa4cbb04c9af9',
            ],
        },
    },
    // Wormhole chain 26 is Pythnet; the emitter is Pyth's accumulator.
    dataSources: [
        { chain: 26, emitter: '507974686e6574507974686e6574507974686e6574507974686e657450797468' },
    ],
};
